// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZnQHcFrNXBqt5QGSXqHeczRo4luVt1Dw',
    appId: '1:184568296872:android:f4165d0ff4276e45f7199d',
    messagingSenderId: '184568296872',
    projectId: 'core-phoenix-489602-b1',
    storageBucket: 'core-phoenix-489602-b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFQJFhcbO_3uMp0iiW3pXazqfIjD41CZY',
    appId: '1:184568296872:ios:67dba56683bfb932f7199d',
    messagingSenderId: '184568296872',
    projectId: 'core-phoenix-489602-b1',
    storageBucket: 'core-phoenix-489602-b1.firebasestorage.app',
    androidClientId: '184568296872-tdu3tof81828k5m1kq3d6mka9n6b38jc.apps.googleusercontent.com',
    iosBundleId: 'com.classroomremaked.classroomRemaked',
  );
}
